name: central

networks:
  default:
    name: central

services:
  auth-webserver:
    build:
      context: .
      dockerfile: auth.Dockerfile
    restart: always
    env_file:
      - ./auth/.env
    volumes:
      - ./auth:/app/auth
      - ./internal:/app/internal
    ports:
      - 5000:5000
    command: air
    depends_on:
      - database

  campaigns-webserver:
    build:
      context: .
      dockerfile: campaigns.Dockerfile
    restart: always
    env_file:
      - ./campaigns/.env
    volumes:
      - ./campaigns:/app/campaigns
      - ./internal:/app/internal
    ports:
      - 5001:5001
    command: air
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: genos
      POSTGRES_PASSWORD: genos
      POSTGRES_MULTIPLE_DATABASES: auth,campaigns
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresDb:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
